CREATE TABLE IF NOT EXISTS teacher(
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  teachername VARCHAR(255),
  college VARCHAR(255),
  mailadress VARCHAR(255),
  gender VARCHAR(255)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
