CREATE TABLE IF NOT EXISTS teacher(
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  teachername VARCHAR(255),
  college VARCHAR(255),
  mailadress VARCHAR(255),
  gender VARCHAR(255)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS student(
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255),
  furi VARCHAR(255),
  school VARCHAR(255),
  age VARCHAR(255),
  mailaddress VARCHAR(255),
  sex VARCHAR(255)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
